### ISSUE TITLE
Display default error pages for 413 errors

### ISSUE THREAD

**Issue by tommotaylor** [ministryofjustice/cloud-platform-infrastructure#328]
Extending from: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/327

When a 413 error is produced, for instance by uploading a >50mb file, the error page should be the default GDS styled one.

This can be set by adding 413 to the following line: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/nginx-ingress-acme.tf#L35

Eg:
```
    custom-http-errors: 400,403,404,413,502,504
```

**Comment by tommotaylor** [comment]
FYI the source of our 413 error is described here: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by AntonyBishop** [comment]
Deployed to Live-1 this morning.
