### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [ministryofjustice/cloud-platform-infrastructure#439]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-suspend-inactive-users/aws-iam-suspend-inactive-users.yaml`

**line number(s):** [52]

**resource(s):** 

IAM policy should not allow * resource with PassRole action

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-suspend-inactive-users/aws-iam-suspend-inactive-users.yaml`

**line number(s):** [73, 157]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-suspend-inactive-users/aws-iam-suspend-inactive-users.yaml`

**line number(s):** [64]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-risk-credentials-exposed/risk_credentials_exposed.serverless.yaml`

**line number(s):** [65, 126, 175, 216, 255]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-user-roles-groups/aws-iam-instanceprofiles.yaml`

**line number(s):** [36]

**resource(s):** 

IAM managed policy should not allow Allow+NotAction

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-user-roles-groups/aws-iam-instanceprofiles.yaml`

**line number(s):** [36, 91, 129, 206, 282]

**resource(s):** 

IAM managed policy should not allow * resource

---

**severity:** warning

**filename:** `./cloudformation/aws-account-baseline-templates/aws-iam-user-roles-groups/aws-iam-instanceprofiles.yaml`

**line number(s):** [36, 91, 129, 206, 282, 16, 71, 109, 186]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

**Comment by digitalronin** [comment]
Hi @ctindall Thank you for taking the time to raise these concerns. I've contacted our security team, who will look into this. We appreciate you making the effort to help us improve our code.

**Comment by obutterbach** [comment]
Hi @ctindall, thank you for submitting this issues, I'm working for the security team here.
Firstly, I appreciate the way you're promoting your services by using a bot which would scan public GitHub repos and open issue reports on these repos.
I also appreciate that we need to promote best practices when writing IAM policy and avoid using wildcards `*` in our resource declaration.
Now, unfortunately your bot flag legitimate codes such as follow:
```
  DenyAllPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: DenyAllPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Effect: "Deny"
          Action: "*"
          Resource: "*"
```
or this:
```
                ...
                  - iam:GetUser
                  - iam:DeleteLoginProfile
                  - iam:DeleteUserPolicy
                  - iam:ListAccessKeys
                  - iam:ListGroupsForUser
                  - iam:ListMFADevices
                  - iam:ListUsers
                  - iam:ListAttachedGroupPolicies
                  - iam:ListAttachedUserPolicies
                  - iam:ListUserPolicies
                  - iam:RemoveUserFromGroup
                  - iam:UpdateAccessKey
                  - sns:Publish
                Resource: "*"
```
Something that even AWS would [document](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_read-only-console.html) and advice to use.
There isn't one-size-fits-all solution, thank you to review this report and make sure that's actually accurate case by case

**Comment by ctindall** [comment]
Thank you for taking the time to explain this! I appreciate the feedback and will be working to improve the service, both by catching cases like these and by motivating me to better review these before letting my bot spam innocents like you!

**Comment by obutterbach** [comment]
Glad that my comment was helpful, I believe we can close this issue now. Don't hesitate to open a new one in our repos if you see any other potential security issues.

**Comment by digitalronin** [comment]
Closing as per conversation above.
