### ISSUE TITLE
Update Readme of EKS cluster 

### ISSUE THREAD

**Issue by poornima-moj** [ministryofjustice/cloud-platform-infrastructure#514]
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/master/terraform/cloud-platform-eks#cloud-platform---eks-cluster

- how to update kubeconfig and access the eks cluster
- how to remove the eks cluster and its components

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/GSK9K0REF/p1579596496002100

**Comment by vijay-veeranki-moj** [comment]
Added guidence in a runbook on accessing EKS cluster:
https://runbooks.cloud-platform.service.justice.gov.uk/access-eks-cluster.html#access-eks-cluster

Updated the runbook to destroy the eks cluster and its components:

https://runbooks.cloud-platform.service.justice.gov.uk/eks-tools-cluster.html#4-delete-the-eks-cluster
