### ISSUE TITLE
Wrong SourceIdentifier for Config Rule

### ISSUE THREAD

**Issue by VictorMPerez** [ministryofjustice/cloud-platform-infrastructure#811]
Awesome code guys, but I found this, the line **813** from file **aws-config-enable-rules.yaml** uses for the rule **rS3BucketServerSideEncryptionEnabledConfigRule** the source identifier S3_BUCKET_PUBLIC_WRITE_PROHIBITED, but it should be **S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED** according to [s3-bucket-server-side-encryption-enabled](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-server-side-encryption-enabled.html )

Thanks in advance,

**Comment by digitalronin** [comment]
This looks like automated job-hunting spam, so I'm closing it. If the author wants to clarify exactly what genuine problem they're reporting, and what the suggested action is, we can revisit.

**Comment by VictorMPerez** [comment]
heheheheh, thanks for the offer bro, but I'm not looking for job, the problem that you have is the line **813** of the file **cloud-platform-infrastructure/cloudformation/aws-account-baseline-templates/aws-config-cloudtrail-logging/aws-config-enable-rules.yaml**, you mention as description "Checks for explicit denies on put-object requests without server side encryption.", basically you're saying that it checks is a bucket is encrypted or no, but you are using an AWS manged rule that checks for public access NOT for SSE, to be clear you are using the wrong rule, and again, really good job, it's awesome.

**Looks like this ritgh now:**
`
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
`

**Should be like this:**
`
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
`
