### ISSUE TITLE
Suggest changing disk full alerting. 

### ISSUE THREAD

**Issue by andy-v-h** [ministryofjustice/cloud-platform-infrastructure#812]
:wave: 

Today I was using your lovely Prom Alerts for inspiration. The disk usage ones are mildly useless as is ( depending on disk size I 'spose). But! basically kubelet will start trying to clean up images before you hit the warning level alert at 85%. Luckily I found this while firedrilling these new alerts.  

In pkg/kubelet/apis/config/types.go
``` go
181 |       // imageGCHighThresholdPercent is the percent of disk usage after which
182 |       // image garbage collection is always run. The percent is calculated as
183 |       // this field value out of 100.
184 |       ImageGCHighThresholdPercent int32
```
and the searching for a default
kubelet/apis/config/v1beta1/defaults.go
```go
129:	if obj.ImageGCHighThresholdPercent == nil {
131:		obj.ImageGCHighThresholdPercent = utilpointer.Int32Ptr(85)
```
Or you can change that on kubelet with the `--image-gc-high-threshold` flag

**Comment by digitalronin** [comment]
This looks like automated job-hunting spam, so I'm closing it. If the author wants to clarify exactly what genuine problem they're reporting, and what the suggested action is, we can revisit.

**Comment by andy-v-h** [comment]
It looks like I found the corrent GitHub org, but the wrong Repo.  My b. https://github.com/ministryofjustice/cloud-platform-prometheus/blob/2a1524c90a030a31a76f74047c5078e92cd4a60e/custom-alerts/custom-alerts.yaml#L85-L100 🤦
